### PR TITLE
fixes for a couple of issues

### PR DESCRIPTION
**Pull request by d-e-s-o**
Hi meh,

I believe I found a couple of issues in the library. Please have a look and merge them as appropriate. It would be great to have a set of unit tests to catch such problems in the future. Do you have any plans for something along those lines?

d-e-s-o

### CODE REVIEW

**Comment by meh** [comment]
About the `get_from` changes, what's the point of returning the ID when it's just been passed as parameter?

About the unit tests, I can't imagine how they would be done since you'd need a HID device attached and know how it works to somewhat test it, but then you'd be testing the device and not the library overall.

**Comment by meh** [comment]
Ah wait, you were referring to `read_from` and not `read`.  The reason `read_from` returns the ID is because it's reading anything and not a specific feature, so you might need to know what the ID is, `read` on the other hand puts the ID at `buffer[0]`.

`get` and `get_from` request a specific feature instead, so you already know the ID since you just gave it to it.

>Set the first byte of data[] to the Report ID of the report to be read. Make sure to allow space for this extra byte in data[]. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].

That's what the documentation says about `hid_get_feature_report`.

**Comment by meh** [comment]
I merged everything except the API change, if you have any other bug fixes feel free to open another pull request.

If you don't please tell me because I'm going to publish a new version otherwise, and do a couple API changes to `get` and `get_from` because I just realized there's no way for them to return `0` so returning an `Option` there is useless.

**Comment by d-e-s-o** [comment]
Awesome, thanks! Yeah, I read a report ID parameter into read_from() that is not there. I agree with your assessment.
I don't have any other changes right now.

**Pull request closed without merging**
